// application "entry point" generated by npm init; required for esm
// didn't add anything here other than these comments
// this is the file you actually run, ie 'node index.js' or 'npm start'
// if you setup a start script in package.json
require = require("esm")(module/*, options*/)
module.exports = require("./main.js")
